// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNdQBDl2XBYpzn5ng1BsirI2fciufjXlk',
    appId: '1:183865338046:web:564ce4d54f355d5f6856ef',
    messagingSenderId: '183865338046',
    projectId: 'yugioh-deck-67dd9',
    authDomain: 'yugioh-deck-67dd9.firebaseapp.com',
    storageBucket: 'yugioh-deck-67dd9.appspot.com',
    measurementId: 'G-63QB66ZN65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCytm5VRmbDwpsAqOVejV_SEXNgcdy99l8',
    appId: '1:183865338046:android:3a86221d30f3b3836856ef',
    messagingSenderId: '183865338046',
    projectId: 'yugioh-deck-67dd9',
    storageBucket: 'yugioh-deck-67dd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Fi1AEt3y1vQNcrBB-tfGUU6zG7-AkbU',
    appId: '1:183865338046:ios:fd5efc0d127f47c06856ef',
    messagingSenderId: '183865338046',
    projectId: 'yugioh-deck-67dd9',
    storageBucket: 'yugioh-deck-67dd9.appspot.com',
    iosBundleId: 'com.bernardopiane.yugiDeck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Fi1AEt3y1vQNcrBB-tfGUU6zG7-AkbU',
    appId: '1:183865338046:ios:fd5efc0d127f47c06856ef',
    messagingSenderId: '183865338046',
    projectId: 'yugioh-deck-67dd9',
    storageBucket: 'yugioh-deck-67dd9.appspot.com',
    iosBundleId: 'com.bernardopiane.yugiDeck',
  );
}
